name: Build and publish Docker images
on:
  release:
    types: [published]


jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Extract metadata (tags, labels) for Docker
          id: metadata
          uses: docker/metadata-action@v5
          with:
            images: |
              ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
            tags: |
              type=samver,pattern={{version}}
              type=samver,pattern={{major}}.{{minor}}
              type=raw,value=latest
        - name: Build and push Docker images
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ steps.metadata.outputs.tags }}
            labels: ${{ steps.metadata.outputs.labels }}
