name: Conditional and Expressions
on: [push, workflow_dispatch, issues, pull_request]
run-name: "Conditional tests by ${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
  test-if-issue-or-pr:
    runs-on: ubuntu-latest
    if: contains(fromJson('["issues", "pull_request"]'), github.event_name)
    steps:
      - run: echo "Hello, world! PR OR issues"
      - name: Run only if issue as bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: echo ${{ join(github.event.issue.labels.*.name, ', ') }}
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Only run on push !
    steps:
      - run: echo "Hello, world!"
