name: Repo Events
on:  [push, pull_request, issues]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo things
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
        uses: actions/checkout@v4