name: Repo Events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues:
    types:
      - opened

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo things
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - name: checkout
        uses: actions/checkout@v4