name: Expression & Contexts
on: [push, workflow_dispatch, issues]

run-name: "Expressions & Contexts by ${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
  expressions-and-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ true }}
          echo ${{ null }}
          echo ${{ 2 > 1 }}
          echo ${{ true || (false && true) }}
      - name: Contexts
        id: contexts
        run: |
          echo '${{ toJson(github)}}'
          echo '${{ toJson(job)}}'
          echo '${{ toJson(secrets)}}'
          echo '${{ toJson(steps)}}'
          echo '${{ toJson(runner)}}'

          