name: File descryption
on: [push, workflow_dispatch]

jobs:
  decrypt-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt files
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_PASSPHRASE" --output $HOME/secrets/secret.json secret.json.gpg
      - name: View encrypted file content
        run: cat $HOME/secrets/secret.json