name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string to test things out
        run: echo "Hello World"
      - name: Multiline Commands
        run: |
          node -v
          npm -v
  parallel:
    runs-on: ubuntu-latest
    steps:
      - name: View OS Informations
        run: uname -a
  depenant-job:
    runs-on: ubuntu-latest
    needs:
      - run-shell-commands
    steps:
      - name: Echo base ubuntu EDITOR value
        run: echo $EDITOR
      - name: Error creator
        run: helmfile -e coolenv apply