name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        required: true
        type: string
        default: "ubuntu-latest, ubuntu-22.04"
      node-version:
        description: 'Node.js version'
        required: true
        type: string
        default: "14,16,18"

jobs:

  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: matri-array
        with:
          script: "return {'os': context.payload.inputs['os'].split(','), 'node-version': context.payload.inputs['node-version'].split(',') }"
          result-encoding: json
      - run: echo '${{ steps.matri-array.outputs.result }}'
      - run: echo "step-output=1" >> $GITHUB_OUTPUT
        id: step-1
      - run: echo "step-output=2" >> $GITHUB_OUTPUT
        id: step-2
      - run: | 
          echo '${{ steps.step-1.outputs.step-output }}'
          echo '${{ steps.step-2.outputs.step-output }}'

  node-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        node-version: [14,16,18]
    runs-on: ${{ matrix.os}}
    steps:
      - run: node -v
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v