name: Matrix
on: [push]

jobs:
  node-matrix:
    
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        node-version: [14,16,18]
        include:
          - os: ubuntu-22.04
            test: true
          - os: macos-latest
            node-version: 18
          - experimental: false
          - os: ubuntu-latest
            node-version: 18
            experimental: true
        exclude:
          - os: ubuntu-22.04
          - os: ubuntu-latest
            node-version: 14
      fail-fast: false
    runs-on: ${{ matrix.os}}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v