name: Status Check
on: [push, workflow_dispatch]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 30
      - name: Step 2
        id: step2
        run: exit 1
      - name: Run on Failure
        if: failure() && steps.step2.conclusion == 'failure'
        run: echo "Failure"
      - name: Run on Success
        if: success() # not needed because it's the default behavior
        run: echo "Success"
      - name: Run on Always
        if: always()
        run: echo "Always"
      - name: Run on Cancelled
        if: cancelled()
        run: echo "Cancelled"

  jobs-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo "Hello, world JOB 2!"